package zero

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"entgo.io/contrib/entproto"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/stretchr/testify/require"
)

func TestGenerate(t *testing.T) {
	tgt := "./target"
	graph, err := entc.LoadGraph("./ent/schema", &gen.Config{
		Target: tgt,
	})
	require.NoError(t, err)

	err = entproto.Generate(graph)
	require.NoError(t, err)

	bytes, err := os.ReadFile(filepath.Join(tgt, "proto", "zero", "zero.proto"))

	require.NoError(t, err)
	require.True(t, strings.Contains(string(bytes), "// Code generated by entproto. DO NOT EDIT."))
}
